version: '3.3'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    restart: always

  app:
    build:
      context: .
    volumes:
      - ./scraper:/scraper
    command: sh -c "python3 etl.py"
    depends_on:
      - selenium